apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app-1
  template:
    metadata:
      labels:
        app: my-app-1
    spec:
      containers:
      - name: my-app-1
        image: mano6692/java-app-v1.25
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: my-app-1
spec:
  selector:
    app: my-app-1
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: NodePort
